[2025-01-26T02:05:40.944+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T02:05:40.985+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T02:05:41.005+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T02:05:41.007+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T02:05:41.049+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_prim_api> on 2025-01-25 00:00:00+00:00
[2025-01-26T02:05:41.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T02:05:41.067+0000] {standard_task_runner.py:72} INFO - Started process 242 to run task
[2025-01-26T02:05:41.067+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prim_pipelines', 'get_data_from_prim_api', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphbmqy1as']
[2025-01-26T02:05:41.068+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask get_data_from_prim_api
[2025-01-26T02:05:41.165+0000] {task_command.py:467} INFO - Running <TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-25T00:00:00+00:00 [running]> on host d9d6adeb4aac
[2025-01-26T02:05:41.292+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prim_pipelines' AIRFLOW_CTX_TASK_ID='get_data_from_prim_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T02:05:41.294+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T02:05:41.971+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T02:05:41.986+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T02:05:41.987+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prim_pipelines, task_id=get_data_from_prim_api, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T020540, end_date=20250126T020541
[2025-01-26T02:05:42.024+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T02:05:42.046+0000] {dagrun.py:977} ERROR - Failed to get task for ti <TaskInstance: prim_pipelines.check_row_numbers__1 scheduled__2025-01-25T00:00:00+00:00 [failed]>. Marking it as removed.
[2025-01-26T02:05:42.069+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T02:05:42.075+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T02:08:40.891+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T02:08:40.921+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T02:08:40.933+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T02:08:40.933+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T02:08:40.947+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_prim_api> on 2025-01-25 00:00:00+00:00
[2025-01-26T02:08:40.961+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T02:08:40.963+0000] {standard_task_runner.py:72} INFO - Started process 363 to run task
[2025-01-26T02:08:40.964+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prim_pipelines', 'get_data_from_prim_api', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9_8rasdh']
[2025-01-26T02:08:40.965+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask get_data_from_prim_api
[2025-01-26T02:08:41.021+0000] {task_command.py:467} INFO - Running <TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-25T00:00:00+00:00 [running]> on host d9d6adeb4aac
[2025-01-26T02:08:41.155+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prim_pipelines' AIRFLOW_CTX_TASK_ID='get_data_from_prim_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T02:08:41.157+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T02:08:41.566+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T02:08:41.584+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T02:08:41.585+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prim_pipelines, task_id=get_data_from_prim_api, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T020840, end_date=20250126T020841
[2025-01-26T02:08:41.622+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T02:08:41.652+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T02:08:41.654+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
