[2025-02-01T23:13:11.141+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T23:13:11.202+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T23:13:11.220+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T23:13:11.221+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T23:13:11.241+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_prim_api> on 2025-01-31 00:00:00+00:00
[2025-02-01T23:13:11.258+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T23:13:11.262+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-02-01T23:13:11.261+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prim_pipelines', 'get_data_from_prim_api', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpta4t_j0y']
[2025-02-01T23:13:11.263+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_data_from_prim_api
[2025-02-01T23:13:11.347+0000] {task_command.py:467} INFO - Running <TaskInstance: prim_pipelines.get_data_from_prim_api scheduled__2025-01-31T00:00:00+00:00 [running]> on host 3f913d7c9c18
[2025-02-01T23:13:11.504+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prim_pipelines' AIRFLOW_CTX_TASK_ID='get_data_from_prim_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-02-01T23:13:11.507+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T23:13:12.202+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-01T23:13:12.221+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T23:13:12.223+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prim_pipelines, task_id=get_data_from_prim_api, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250201T231311, end_date=20250201T231312
[2025-02-01T23:13:12.302+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T23:13:12.345+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-01T23:13:12.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
