[2025-01-25T13:28:40.773+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T13:28:40.827+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api manual__2025-01-25T13:28:36.534272+00:00 [queued]>
[2025-01-25T13:28:40.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prim_pipelines.get_data_from_prim_api manual__2025-01-25T13:28:36.534272+00:00 [queued]>
[2025-01-25T13:28:40.843+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T13:28:40.861+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_data_from_prim_api> on 2025-01-25 13:28:36.534272+00:00
[2025-01-25T13:28:40.884+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=459) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-25T13:28:40.887+0000] {standard_task_runner.py:72} INFO - Started process 474 to run task
[2025-01-25T13:28:40.886+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prim_pipelines', 'get_data_from_prim_api', 'manual__2025-01-25T13:28:36.534272+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4dkkbalq']
[2025-01-25T13:28:40.888+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask get_data_from_prim_api
[2025-01-25T13:28:40.955+0000] {task_command.py:467} INFO - Running <TaskInstance: prim_pipelines.get_data_from_prim_api manual__2025-01-25T13:28:36.534272+00:00 [running]> on host 51421c3b86a4
[2025-01-25T13:28:41.052+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prim_pipelines' AIRFLOW_CTX_TASK_ID='get_data_from_prim_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T13:28:36.534272+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-25T13:28:36.534272+00:00'
[2025-01-25T13:28:41.054+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T13:28:41.534+0000] {python.py:240} INFO - Done. Returned value was: dags/data/data.json
[2025-01-25T13:28:41.570+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T13:28:41.571+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prim_pipelines, task_id=get_data_from_prim_api, run_id=manual__2025-01-25T13:28:36.534272+00:00, execution_date=20250125T132836, start_date=20250125T132840, end_date=20250125T132841
[2025-01-25T13:28:41.634+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T13:28:41.705+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-25T13:28:41.709+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
